### PR TITLE
Add email setup test functionality

### LINKED ISSUE #396: Feature: send test email
**Description:**
Add a link "Send test email" to the "Administer Users" admin page which will trigger sending an email to the admin user's configured email address. This is useful to diagnose email configuration problems in LibreClinica.

**Requirements:**
Admin with email address configured in Administration - Users - Edit

**Steps to follow:**
1. login as admin
1. from the tasks menu select Administration - Users
1. click "Send test email"

**Expected result:**
See screenshots #395

### PR DESCRIPTION
**Pull request by ghost**
This PR adds a link "Send test email" to the "Administer Users" admin page which will trigger sending an email to the admin user's configured email address.

### Users Page
users page

### Sending email succeeded
success

### Test email
email

### Sending email failed
error

### CODE REVIEW

**Comment by toskrip** [comment]
Looks good from the first look on it. I made one comment which is related to resources as all other links use capitalized first letter and but the newly added one now looks a bit different from the rest of GUI. But I still want to test it just to make sure before merge. For this one as it is new feature we definitely need also issue created that will be linked with PR.

**Comment by cedric-v3** [comment]
Thanks for your comments, @toskrip. It took me some time to understand what you meant, but I think you were talking about "Send test email" not using title case style, right? I've just pushed a fix for this.

I've looked into creating an issue for this PR, but can only select between "Bug report" and "Report a security vulnerability". Should I open a bug report, even it is a feature request? Would it make sense, if you, @oba-reliatec, opens the issue since the feature was requested by you?

**Comment by toskrip** [comment]
tnx for correction, that is right, now it looks consistent.

**Comment by oba-reliatec** [comment]
> I've looked into creating an issue for this PR, but can only select between "Bug report" and "Report a security vulnerability". Should I open a bug report, even it is a feature request? Would it make sense, if you, @oba-reliatec, opens the issue since the feature was requested by you?

Thank you Cedric and Tomas for implementing and reviewing the test email feature. I created an issue for it #396.

**Review by toskrip — APPROVED** [review]
ok

**Pull request merged**
