### PR TITLE
Update release-notes.txt

### PR DESCRIPTION
**Pull request by oba-reliatec**
What about the sentence about SOAP?
As you suggested, we could leave the file away completely, as system requirements are stated on https://libreclinica.org/download.html. However, shouldn't a software repo include software requirements?

### CODE REVIEW

**Comment by toskrip** [comment]
I was initially asking because, it looks to me that we need to do some more cleanup in the repository root as we have with redundant information there e.g. VERSION file (the actual version should be visible for top of the CHANGELOG. If we want to maintain system requirements in repo, then these should probably go to README (would make sense, also we could add then statement about SOAP ws to be legacy - not developed further). CHANGELOG should not be only actual release but prior release changelogs data as well (sorted with newest on top). Contributors in README, what I usually seen in other projects, it is only simple list. Further details e.g. who contributed what is then listed in CHANGELOG if needed.

**Comment by toskrip** [comment]
We currently do not publish web documentation for API but also apidoc.json should be adapted as well to reflect the forked project name.

**Comment by oba-reliatec** [comment]
Ok, so what do you suggest (here is, what I understand):
* VERSION  
This file just contains the version number. I think it is needed by automatisms like the bump-version skript. Otherwise I have no problem to delete it.
* CHANGELOG  
is kept the way you suggested. In the next release, I will keep the contents for the older versions
* release-notes.txt  
go to README, delete release-notes.txt
* README  
stays, see pull request #291
* apidoc.json  
As long as we do not change the API and do not have our own API documentation, in my opinion, it is most useful to the user or developer, if we keep the apidoc.json of OpenClinica. But I guess you have more experience in that. Looking at the file, I can see neither content documenting the API nor a link to the documentation. Maybe some IDE or build tools can? Advice is welcome.
* anything else to delete :smile_cat: ?

**Comment by toskrip** [comment]
Sounds good, if you have a script to bump version that is based on VERSION, then of course it needs to stay.

apidoc.json - it is project descriptor, it is used for generation of web based API documentation, if somebody runs apidoc against the source code of LC project it will generate a web page (API documentation) with project name as specified in that descriptor, it does not have any function for LC itself, we can as well remove it if we do not want to publish web API documentation.

**Comment by oba-reliatec** [comment]
Ok, deleted release-notes.txt 4a410b40dbe413b1086b97af4ee03820c636e61c thank you for including it in README.

VERSION  
Actually I learned this from your documentation on https://libreclinica-docs.readthedocs.io/en/latest/dev/developer.html#release-branches and eventually wanted to ask you, which bump-version.sh you use. I used a version I found on GitHub last time.

apidoc.json  
As LC has an API I find it useful, if such mechanism you described delivers some documentation. And as long as we have neither reviewed it nor written our own for LibreClinica, I would prefer to leave it, showing it comes from OC.

**Review by toskrip — APPROVED** [review]
ok

**Pull request merged**
