### PR TITLE
issue 39: Error page shown upon opening Default Study

### PR DESCRIPTION
**Pull request by toskrip**
issue 39: Error page shown upon opening Default Study

### CODE REVIEW

**Comment by toskrip** [comment]
tested according the workflow in issue 39. After review, candidate for merge to lc-develop.

**Comment by toskrip** [comment]
Removed small code maintancance (as requested, will be eventually part of different pull request). Throwing exception in constructor would be even more drastical (application unable to deploy when the cache is not fully initalized accordig the config in core - because of initial dependecy injection for RandomizationService). As an alternative I propose thorwing exception on cache usage and handle it in ViewStudyServlet.

**Comment by toskrip** [comment]
Randomization removed from LC. (Not initialized cache for randomization will no longer cause the error described in ticket).

**Comment by chae-reliatec** [comment]
related to issue #51

**Pull request merged**
