### PR TITLE
Lc develop admin manual

### PR DESCRIPTION
**Pull request by hillgert**
Finally finished our part of the new administrator manual. Also pdf manuals will be generated by default as they are referenced within the application depending on the user's role.

### CODE REVIEW

**Comment by oba-reliatec** [comment]
What happens, if project is built with Maven profile "exclude-pdf-manuals". Will users end up on a dead link when selecting download manual from the Tasks menu? The best solution would be to omit the "Manual download" section in the Tasks menu if exclude-pdf-manuals is activated (default), and to control this via an entry in the datainfo.properties config file.

**Review by toskrip — APPROVED** [review]
Looks good!

**Comment by toskrip** [comment]
The conflicts are resolved so it can be merged. However I did change the default behaviour to exclude-pdf-manuals by default. We had this discussion prior. The current conversion of markdown to pdf depends on node with npm and by default we do not want to force developers to fetch the whole node + npm environment when building.

**Comment by hillgert** [comment]
No problem with changing the default behaviour as long as there will be two distributions. One with and one without the PDF manuals contained.

**Pull request merged**
