### PR TITLE
t006 added

### PR DESCRIPTION
**Pull request by GerbenRienk**
A brand new test-file about events

### CODE REVIEW

**Comment by GerbenRienk** [comment]
Aaah, I see. My bad, sorry about that. Shall I correct it and make a new pull-request? Or do you prefer to  make an issue first?

**Comment by chae-reliatec** [comment]
Just update the code and commit it. This is sufficient.

**Comment by GerbenRienk** [comment]
I made the canges and committed it. Could you review and merge?
May thanks.

**Comment by chae-reliatec** [comment]
target issue #69

**Pull request merged**
