### PR TITLE
updated spring from '3.0.5.RELEASE' to '5.1.4.RELEASE'

### PR DESCRIPTION
**Pull request by oba-reliatec**
the database isn't updated automatically for now

### CODE REVIEW

**Comment by oba-reliatec** [comment]
this resolves issue #4

**Comment by oba-reliatec** [comment]
Please add the automatic database update first.

**Comment by chae-reliatec** [comment]
lc-spring5 has been merged into lc-develop

**Comment by oba-reliatec** [comment]
# DQ-Report
## Objective
Update the Spring-Libraries from version 3 to version 5.
## Reason for change
To improve stability, security, and to allow LibreClinica to build from freely available repositories. The currently used version has known security issues.
## Technical description
Changed version in Maven configuration files for Spring and its dependencies. Source code edited to fit with the API of the updated libraries.
# DQ-Tests
## migrate from OpenClinica-3.14 to LibreClinica-1.0.0 (database contains an empty study)
### description
Check if the migration from an existing OpenClinica-3.14 installation to LibreClinica-1.0 works.
precondition
OpenClinica-3.14 is installed and the Default study is set up but empty
### workflow
1. uninstall OpenClinica-3.14
1. restart tomcat
1. install LibreClinica-1.0.0
1. check if the login page is displayed (check A)
1. check if the login works (check B)
### expected result when error free
the login works as expected
### expected result when malfunctioning
LibreClinica can not be started and the login page can't be displayed
## install LibreClinica-3.14 (database is empty)
Check if the installation from LibreClinica-1.0 works.
### precondition
\-
### workflow
1. install LibreClinica-1.0.0
2. check if the login page is displayed (check A)
3. check if the login works (check B)
### expected result when error free
the login works as expected
### expected result when malfunctioning
LibreClinica can not be started and the login page can't be displayed

**Pull request closed without merging**
